#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# Remove any existing the default configuration file
rm /etc/nginx/sites-enabled/default

# Configure nginx to listen to port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
