#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# create a symbolic link (-s option) between the nginx configuration file
# and enable sitess directory

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminates the first nginx process ID 
kill "$(pgrep 'nginx' | head -1)"
